apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak
data:
  KC_DB: "postgres"
  KC_DB_URL: "jdbc:postgresql://postgres-stateful-0.postgres-service.default.svc.cluster.local:5432/keycloak"
  KC_HEALTH_ENABLED: "true"
  KC_METRICS_ENABLED: "true"